# Airtable Vars
API_KEY = "API_KEY"
DB_AIRTABLE_ID = "DB_AIRTABLE_ID"
TABLE_NAMES = ['Twitter Telegram']

# TELEGRAM token
BOT_TOKEN = '1BOT_TOKEN'

# Twitter API
TWITTER_CONSUMER_KEY = "TWITTER_CONSUMER_KEY"
TWITTER_CONSUMER_SECRET = "TWITTER_CONSUMER_SECRET"
# optionally
TWITTER_ACCESS_TOKEN = "TWITTER_ACCESS_TOKEN"
TWITTER_ACCESS_TOKEN_SECRET = "TWITTER_ACCESS_TOKEN_SECRET"
